apiVersion: apiserver.config.k8s.io/v1
kind: AuthenticationConfiguration
jwt:
  - issuer:
      url: https://token.actions.githubusercontent.com
      audiences:
        - oidc-github-action
      audienceMatchPolicy: MatchAny
    claimMappings:
      username:
        claim: sub
        prefix: "github:"