apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  workshop.server: |
    workshop.nm.internal:53 {
      errors
      cache 30
      forward . 31.70.86.126
    } 
    vpn.nm.internal:53 {
      errors
      cache 30
      forward . 31.70.86.126
    }
