{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "webapp.fullname" . }}-ingressroute
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`{{ .Values.ingressRoute.host}}`)
    kind: Rule
    services:
    - name: {{ include "webapp.fullname" . }}
      port: 80
{{- end }}