name: Build LED Matrix for Raspberry PI
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'led-matrix/**'

permissions: 
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: container-fun.led-matrix

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        dotnet restore led-matrix/src/led-matrix.csproj
    - name: Build
      run: |
        dotnet build --no-restore led-matrix/src/led-matrix.csproj
    - name: Publish
      run: |
        dotnet publish -c release -r linux-arm --no-self-contained -o led-matrix/arm led-matrix/src/led-matrix.csproj

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
         images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
         tags: |
          type=raw,value=1.0.0
          type=raw,value=latest
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./led-matrix
        platforms: linux/arm/v7
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

