name: Build Custom HPA
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'custom-hpa/**'

permissions: 
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: container-training.custom-hpa

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        dotnet restore custom-hpa/Manager/src/Manager.csproj
        dotnet restore custom-hpa/Worker/src/Worker.csproj
    - name: Build
      run: |
        dotnet build --no-restore custom-hpa/Manager/src/Manager.csproj
        dotnet build --no-restore custom-hpa/Worker/src/Worker.csproj
    - name: Publish
      run: |
        dotnet publish -c release -r linux-x64 --no-self-contained -o custom-hpa/Manager/amd64 custom-hpa/Manager/src/Manager.csproj
        dotnet publish -c release -r linux-x64 --no-self-contained -o custom-hpa/Worker/amd64 custom-hpa/Worker/src/Worker.csproj
    - name: Publish
      run: |
        dotnet publish -c release -r linux-arm64 --no-self-contained -o custom-hpa/Manager/arm64 custom-hpa/Manager/src/Manager.csproj
        dotnet publish -c release -r linux-arm64 --no-self-contained -o custom-hpa/Worker/arm64 custom-hpa/Worker/src/Worker.csproj

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta-manager
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=manager
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./custom-hpa/Manager
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta-manager.outputs.tags }}
        labels: ${{ steps.meta-manager.outputs.labels }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta-worker
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=worker
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./custom-hpa/Worker
        provenance: false
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta-worker.outputs.tags }}
        labels: ${{ steps.meta-worker.outputs.labels }}

