name: Build Initializer
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'initializer/**'

permissions: 
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: container-training.initializer

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        dotnet restore initializer/init/src/init.csproj
        dotnet restore initializer/main/src/main.csproj
    - name: Build
      run: |
        dotnet build --no-restore initializer/init/src/init.csproj
        dotnet build --no-restore initializer/main/src/main.csproj
    - name: Publish
      run: |
        dotnet publish -c release -r linux-x64 --no-self-contained -o initializer/init/amd64 initializer/init/src/init.csproj
        dotnet publish -c release -r linux-x64 --no-self-contained -o initializer/main/amd64 initializer/main/src/main.csproj
    - name: Publish
      run: |
        dotnet publish -c release -r linux-arm64 --no-self-contained -o initializer/init/arm64 initializer/init/src/init.csproj
        dotnet publish -c release -r linux-arm64 --no-self-contained -o initializer/main/arm64 initializer/main/src/main.csproj

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta-init
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=init
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./initializer/init
        provenance: false
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta-init.outputs.tags }}
        labels: ${{ steps.meta-init.outputs.labels }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta-main
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=main
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./initializer/main
        provenance: false
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta-main.outputs.tags }}
        labels: ${{ steps.meta-main.outputs.labels }}

