name: Build Tools AMD64
on:
  push:
    branches: [ main ]

permissions: 
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: container-training.tools

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
         images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
         tags: |
           type=raw,value=latest
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./tools
        file: ./tools/Dockerfile.arm64
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
      