name: Build Tools
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'tools/**'

permissions: 
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: container-training.tools

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta-amd64
      uses: docker/metadata-action@v5
      with:
         images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
         tags: |
           type=raw,value=linux-amd64
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./tools
        file: ./tools/Dockerfile.amd64
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta-amd64.outputs.tags }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta-arm64
      uses: docker/metadata-action@v5
      with:
         images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
         tags: |
           type=raw,value=linux-arm64
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./tools
        file: ./tools/Dockerfile.arm64
        platforms: linux/arm64
        push: true
        tags: ${{ steps.meta-arm64.outputs.tags }}
      