name: Build WebApp Common
on:
  workflow_call:
    inputs:
      image-version:
        required: true
        type: string
      build-context:
        required: true
        type: string
        
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: container-training.webapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
         images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
         tags: ${{ inputs.image-version }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.build-context }}
        provenance: false
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}