name: Build WebApp
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'webapp/**'

permissions: 
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: container-training.webapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker v1
      id: meta-v1
      uses: docker/metadata-action@v5
      with:
         images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
         tags: |
           type=raw,value=1.0.0
    - name: Build and push v1
      uses: docker/build-push-action@v5
      with:
        context: ./webapp/v1
        provenance: false
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ steps.meta-v1.outputs.tags }}
        labels: ${{ steps.meta-v1.outputs.labels }}
    - name: Extract metadata (tags, labels) for Docker v2
      id: meta-v2
      uses: docker/metadata-action@v5
      with:
         images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
         tags: |
           type=raw,value=2.0.0
    - name: Build and push v2
      uses: docker/build-push-action@v5
      with:
        context: ./webapp/v2
        provenance: false
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ steps.meta-v2.outputs.tags }}
        labels: ${{ steps.meta-v2.outputs.labels }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta-v3
      uses: docker/metadata-action@v5
      with:
         images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
         tags: |
           type=raw,value=3.0.0
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./webapp/v3
        provenance: false
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ steps.meta-v3.outputs.tags }}
        labels: ${{ steps.meta-v3.outputs.labels }}
