name: Build WebApp
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'webapp/**'

permissions: 
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build-webapp-common.yml
    with:
      image-version: type=raw,value=1.0.0
      build-context: ./webapp/v1