name: Build CityTrip static
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'citytrip/assets/**'
      - 'citytrip/internal/**'

permissions: 
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: container-training.citytrip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker internal
      id: meta-internal
      uses: docker/metadata-action@v5
      with:
         images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
         tags: |
           type=raw,value=internal
    - name: Build and push internal
      uses: docker/build-push-action@v5
      with:
        context: ./citytrip/internal
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ steps.meta-internal.outputs.tags }}
        labels: ${{ steps.meta-internal.outputs.labels }}
    - name: Extract metadata (tags, labels) for Docker assets
      id: meta-assets
      uses: docker/metadata-action@v5
      with:
         images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
         tags: |
           type=raw,value=assets
    - name: Build and push assets
      uses: docker/build-push-action@v5
      with:
        context: ./citytrip/assets
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ steps.meta-assets.outputs.tags }}
        labels: ${{ steps.meta-assets.outputs.labels }}