name: Cleaup untagged images
on:
  workflow_dispatch:

permissions: 
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'container-training.webapp'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with:
            package-name: 'container-training.utils'
            package-type: 'container'
            min-versions-to-keep: 0
            delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'container-training.coffeemaker'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'container-training.citytrip'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'container-training.tools'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'shellinabox'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'codeserver'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'