name: Cleaup untagged images
on:
  workflow_dispatch:

permissions: 
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'webapp'
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with:
            package-name: 'monitoring-for-devops'
            package-type: 'container'
            min-versions-to-keep: 1
            delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with:
            package-name: 'kxs-for-developers'
            package-type: 'container'
            min-versions-to-keep: 1
            delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'kxs-for-developers'
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'container-training.citytrip'
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'container-training.tools'
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'shellinabox'
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'